apiVersion: 1

deleteDatasources:
  - name: Elemer PostgreSQL
    orgId: 1

datasources:
  - name: Elemer PostgreSQL
    uid: elemer-postgres
    orgId: 1
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${ELEMER_DB_NAME}
    user: ${ELEMER_DB_USER}
    isDefault: true
    editable: true
    jsonData:
      database: ${ELEMER_DB_NAME}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: ${ELEMER_DB_PASSWORD}

